CMD = function(){
    ON_NEW_MESSAGE = "ON_NEW_MESSAGE",
    ON_EDIT_MESSAGE = "ON_EDIT_MESSAGE",
    ON_DELETE_MESSAGE = "ON_DELETE_MESSAGE",
    ON_LEAVE_CHAT = "ON_LEAVE_CHAT",
    ON_JOIN_CHAT = "ON_JOIN_CHAT";
}